# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBgColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Item Background Color',
                'verbose_name_plural': 'Items Background Colors',
            },
        ),
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='about_items')),
                ('color', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Services.ServiceBgColor')),
            ],
            options={
                'verbose_name': 'Service Item',
                'verbose_name_plural': 'Services Items',
            },
        ),
    ]
